esphome:
  name: bedroom
  platform: ESP32
  board: esp-wrover-kit


wifi:
  ssid: "My Wifi"
  password: "12345"


# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "1234"

ota:
  password: "1234"


sensor:
  - platform: dht
    pin: 04
    model: DHT11
    temperature:
      name: "BedRoom Temperature"
      filters: 
        - offset: 0.0
    humidity:
      name: "BedRoom Humidity"
    update_interval: 30s

